.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-FISHFILE" "5" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-fishfile\fR \- Fishfile Format
.
.SH "SYNOPSIS"
Fishfiles let you share plugin configurations across multiple installations, let plugins declare dependencies and teach Fisherman what plugins are currently enabled / disabled when using \fBfisher \-\-list\fR\.
.
.P
Your fishfile is stored in \fB$fisher_config/fishfile\fR by default, but you can customize this location overriding the \fB$fisher_file\fR variable in your fish configuration file\.
.
.SH "USAGE"
Fishfiles list one or more plugins by their name, URL or path to a local project\.
.
.P
Here is an example:
.
.IP "" 4
.
.nf

# Ahoy!

gitio
fishtape
shark
get
some_user/her_plugin
.
.fi
.
.IP "" 0
.
.P
A fishfile may contain any amount of whitespace and comments\.
.
.P
If you need to parse a fishfile to list its plugins, for example, to pipe the input into \fBfisher install\fR or \fBfisher update\fR, you can use \fBfisher \-\-list=path/to/fishfile\fR\. Notice that Oh My Fish! bundle file syntax is also supported\.
.
.SH "PLUGINS"
Plugins may list any number of dependencies to other plugins in a fishfile at the root of the project\.
.
.P
When a plugin is installed, its dependencies are downloaded for the first time\. If a dependency is already installed, it is not updated in order to prevent breaking other plugins using a different version\. Currently, uninstalling a plugin does not remove any its dependencies either\.
.
.P
To understand this behavior, it helps to recall the shell\'s single scope for functions\. The lack of private functions means that, it is \fInot\fR possible to single\-lock a specific dependency version\. See also \fBFlat Tree\fR in \fBfisher help tour\fR\.
.
.SH "SEE ALSO"
fisher(1)
.
.br
fisher help config
.
.br

