.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-CONFIG" "7" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-config\fR \- Fisherman Configuration
.
.SH "SYNOPSIS"
This document describes how to use Fisherman configuration variables\.
.
.SH "DESCRIPTION"
Your fish user configuration, usually located in \fB$XDG_CONFIG_HOME/fish/config\.fish\fR is updated after installing Fisherman to add the global variables \fB$fisher_home\fR and \fB$fisher_config\fR\.
.
.P
Using the following variables, you can customize the locations of the cache, index URL, fishfile, create command aliases, etc\.
.
.SH "VARIABLES"
.
.TP
\fB$fisher_home\fR
The home directory\. If you installed Fisherman using the recommended method \fBcurl \-sL install\.fisherman\.sh | fish\fR, the location will be \fB$XDG_DATA_HOME/fisherman\fR\. If you clone Fisherman and run \fBmake\fR yourself, \fB$fisher_home\fR will the current working directory\.
.
.TP
\fB$fisher_config\fR
The user configuration directory\. This is default location of your user \fIfishfile\fR, Fisherman \fIkey_bindings\.fish\fR file and the \fIcache\fR, \fIfunctions\fR, \fIcompletions\fR and \fIconf\.d\fR directories\. \fB$XDG_CONFIG_HOME/fisherman\fR by default\.
.
.TP
\fB$fisher_file\fR
This file keeps a list of what plugins you have installed and are currently enabled\. \fB$fisher_config/fishfile\fR by default\. See \fBfisher help fishfile\fR for details\.
.
.TP
\fB$fisher_cache\fR
The cache directory\. Plugins are downloaded first here and installed to \fB$fisher_config/functions\fR afterwards\. The cache is \fB$fisher_config/cache\fR by default\.
.
.TP
\fB$fisher_index\fR
The URL to the index database\. To use a different index set this to a file or URL\. Redirect URLs are currently not supported due to security and performance concerns\. The underlying request and fetch mechanism is based in \fBcurl\fR(1)\.
.
.TP
\fB$fisher_alias command=alias[,\.\.\.] [command2=alias[,\.\.\.]]\fR
Use this variable to define custom aliases for fisher commands\. See \fBExamples\fR below\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Create aliases for fisher \fBinstall\fR to \fIi\fR, \fIin\fR and \fIinst\fR; and for fisher \fBupdate\fR to \fIup\fR\.
.
.IP "" 0
.
.IP "" 4
.
.nf

set fisher_alias install=i,in,inst update=up
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
\fBfisher help tour\fR
