.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-UPDATE" "1" "January 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-update\fR \- Fisherman Update Manager
.
.SH "SYNOPSIS"
fisher \fBupdate\fR [\fIname\fR, \fIurl\fR or \fIpath\fR \.\.\.]
.
.br
fisher \fBupdate\fR [\fB\-\-quiet\fR] [\fB\-\-help\fR]
.
.br
.
.SH "USAGE"
fisher \fBupdate\fR \fIplugin\fR \.\.\.
.
.br
fisher \fBupdate\fR \fIowner/repo\fR \.\.\.
.
.br
fisher \fBupdate\fR \fIpath\fR \.\.\.
.
.br
.
.SH "DESCRIPTION"
Update one or \fImore\fR plugins by \fIname\fR, searching \fB$fisher_index\fR or by \fIurl\fR\. If no arguments are given, update Fisherman by default\. If you try to update a plugin that is currently disabled, but downloaded to the cache, it will be updated and then enabled\. Use a dash \fB\-\fR to read from the standard input\.
.
.P
If a plugin is missing dependencies, they will be installed\. If any dependencies are already installed they will not be updated\. See \fBfisher help fishfile\fR#{\fBPlugins\fR}\.
.
.SH "OPTIONS"
.
.TP
\fB\-q\fR \fB\-\-quiet\fR
Enable quiet mode\.
.
.TP
\fB\-h\fR \fB\-\-help\fR
Show usage help\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Update all plugins in the cache\.
.
.IP "" 0
.
.P
fisher \-\-list | fisher update \-
.
.SH "SEE ALSO"
\fBfisher\fR(1)
.
.br
\fBfisher help fishfile\fR#{\fBPlugins\fR}
.
.br
\fBfisher help plugins\fR
.
.br

