.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-INSTALL" "1" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-install\fR \- Install Plugins
.
.SH "SYNOPSIS"
fisher \fBinstall\fR [\fIplugins\fR \.\.\.] [\fB\-\-force\fR] [\fB\-\-quiet\fR] [\fB\-\-help\fR]
.
.SH "USAGE"
fisher \fBinstall\fR \fIurl\fR \.\.\.
.
.br
fisher \fBinstall\fR \fIname\fR \.\.\.
.
.br
fisher \fBinstall\fR \fIpath\fR \.\.\.
.
.br
fisher \fBinstall\fR \fIowner/repo\fR \.\.\.
.
.br
.
.SH "DESCRIPTION"
Install one or more plugins, by name, URL or a local path\. If no arguments are given, read the standard input\.
.
.P
In addition, all of the following \fBowner/repo\fR variations are accepted:
.
.IP "\(bu" 4
owner/repo \fB>\fR https://github\.com/owner/repo
.
.br

.
.IP "\(bu" 4
\fIgithub\fR/owner/repo \fB>\fR https://github\.com/owner/repo
.
.br

.
.IP "\(bu" 4
\fIgh\fR/owner/repo \fB>\fR https://github\.com/owner/repo
.
.br

.
.IP "" 0
.
.P
Shortcuts to other common Git repository hosting services are also available:
.
.IP "\(bu" 4
\fIbb\fR/owner/repo \fB>\fR https://bitbucket\.org/owner/repo
.
.br

.
.IP "\(bu" 4
\fIgl\fR/owner/repo \fB>\fR https://gitlab\.com/owner/repo
.
.br

.
.IP "\(bu" 4
\fIomf\fR/owner/repo \fB>\fR https://github\.com/oh\-my\-fish/repo
.
.br

.
.IP "" 0
.
.P
If a URL is given, the repository is cloned to \fB$fisher_cache\fR the first time and any relevant plugin files are copied to \fB$fisher_config\fR functions, completions, conf\.d and man directories\.
.
.P
If the plugin already exists in \fB$fisher_cache\fR, the files are only copied to \fB$fisher_config\fR\. To update a plugin use \fBfisher update\fR\.
.
.P
If the plugin declares dependencies, these will be installed too\. If any of the dependencies are already enabled or downloaded to the cache, they will not be updated to prevent version issues\. See \fIPlugins\fR in \fBfisher help fishfile\fR\.
.
.P
If a plugin includes either a \fBfish_prompt\.fish\fR or \fBfish_right_prompt\.fish\fR, both files are first removed from \fB$fisher_config/functions\fR and then the new ones are copied\.
.
.SH "OPTIONS"
.
.TP
\fB\-f\fR \fB\-\-force\fR
Reinstall given plugin/s\. If the plugin is already in the cache, it will be installed from the cache\.
.
.TP
\fB\-q\fR \fB\-\-quiet\fR
Enable quiet mode\.
.
.TP
\fB\-h\fR \fB\-\-help\fR
Show usage help\.
.
.SH "EXAMPLES"
Here is the directory tree of \fImy_plugin\fR:
.
.IP "" 4
.
.nf

my_plugin
|\-\- README\.md
|\-\- my_plugin\.fish
|\-\- functions
|   |\-\- my_plugin_helper\.fish
|\-\- completions
|   |\-\- my_plugin\.fish
|\-\- test
|   |\-\- my_plugin\.fish
|\-\- man
    |\-\- man1
        |\-\- my_plugin\.1
.
.fi
.
.IP "" 0
.
.P
And here is the directory tree of \fB$fisher_config/\fR after running \fBfisher install my_plugin\fR:
.
.IP "" 4
.
.nf

$fisher_config
|\-\- functions
    |\-\- my_plugin\.fish
    |\-\- my_plugin_helper\.fish
|\-\- completions
    |\-\- my_plugin\.fish
|\-\- man
    |\-\- man1
        |\-\- my_plugin\.1
|\-\- cache
    |\-\- my_other_plugin
    |\-\- my_plugin/\.\.\.
.
.fi
.
.IP "" 0
.
.P
In addition, any \fBinit\.fish\fR and \fB*\.config\.fish\fR files, are copied to \fB$fisher_config/conf\.d\fR and evaluated during the start of the shell\.
.
.P
To prevent name collisions, \fBinit\.fish\fR files are renamed to \fBmy_plugin\.init\.fish\fR\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Install plugins from multiple sources\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher install fishtape simnalamburt/shellder ~/plugins/my_plugin
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
fisher(1)
.
.br
fisher help config
.
.br
fisher help update
.
.br
fisher help uninstall
.
.br

