.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-UNINSTALL" "1" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-uninstall\fR \- Uninstall plugins
.
.SH "SYNOPSIS"
fisher uninstall [\fIplugins\fR \.\.\.]
.
.br
fisher uninstall [\-\-force] [\-\-quiet] [\-\-help]
.
.br
.
.SH "USAGE"
fisher uninstall \fIurl\fR
.
.br
fisher uninstall \fIname\fR
.
.br
fisher uninstall \fIpath\fR
.
.br
fisher uninstall \fIowner/repo\fR
.
.br
.
.SH "DESCRIPTION"
Uninstall one or more plugins, by name, URL or path\. If no arguments are given, read the standard input\. This process is the inverse of Install\.
.
.P
Uninstall does not remove any copies of the given plugin in $fisher_cache\. To erase the copy from the cache, use the \-\-force option\.
.
.P
Uninstall does not remove any dependencies installed with other plugins\. This behavior prevents breaking plugins that share the same dependency\.
.
.SH "OPTIONS"
.
.TP
\-f, \-\-force
Delete copy from cache\.
.
.TP
\-q, \-\-quiet
Enable quiet mode\.
.
.TP
\-h, \-\-help
Show usage help\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Uninstall all plugins and flush the cache\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher \-\-list | fisher uninstall \-\-force
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
fisher help install
.
.br

