.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-LIST" "1" "March 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-list\fR \- List installed plugins
.
.SH "SYNOPSIS"
fisher list [\fIfile\fR]
.
.br
fisher list [\-\-bare] [\-\-link] [\-\-enabled] [\-\-disabled] [\-\-help]
.
.br
.
.SH "USAGE"
fisher list [\fIfile\fR]
.
.SH "DESCRIPTION"
The list command displays all the plugins you have installed\.
.
.IP "" 4
.
.nf

fisher list
  debug
* fishtape
* spin
> superman
@ wipe
.
.fi
.
.IP "" 0
.
.P
The legend consists of:
.
.P
\fB*\fR Indicate the plugin is installed
.
.br
\fB>\fR Indicate the plugin is a prompt
.
.br
\fB@\fR Indicate the plugin is a symbolic link
.
.br
.
.SH "OPTIONS"
.
.TP
\-b, \-\-bare
List plugin without decorators
.
.TP
\-l, \-\-link
List plugins that are symbolic links
.
.TP
\-\-enabled
List plugins that are enabled
.
.TP
\-\-disabled
List plugins that are disabled
.
.TP
\-h, \-\-help
Show usage help
.
.SH "SEE ALSO"
fisher help search
.
.br

