.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-HELP" "1" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-help\fR \- Show Help
.
.SH "SYNOPSIS"
fisher \fBhelp\fR [\fIkeyword\fR] [\fB\-\-all\fR] [\fB\-\-guides\fR] [\fB\-\-usage\fR[=\fIcommand\fR]] [\fB\-\-help\fR]
.
.br
.
.SH "USAGE"
fisher \fBhelp\fR \fIcommand\fR
.
.br
fisher \fBhelp\fR \fIguide\fR
.
.br
fisher \fBhelp\fR \fB\-\-usage\fR=[\fIcommand\fR]
.
.br
.
.SH "DESCRIPTION"
Help displays \fIcommand\fR documentation, usage, guides and tutorials\.
.
.P
Help is based in \fBman\fR(1) pages\. To supply help with your own plugin or command, create one or more man\.1~7 pages and add them to your project under the corresponding man/man% directory\.
.
.IP "" 4
.
.nf

my_plugin
|\-\- my_plugin\.fish
`\-\- man
    `\-\- man1
        `\-\- my_plugin\.1
.
.fi
.
.IP "" 0
.
.P
Help for my_plugin is now available via \fBman\fR(1)\. To add documentation to a \fBfisher\fR command, prepend the keyword \fBfisher\-\fR to the man file, e\.g\., \fBfisher\-my\-command\.1\fR\. This will teach Fisherman how to access the man page using \fBfisher help my\-command\fR\.
.
.P
There are utilities that can help you generate man pages from other text formats, such as Markdown\. One example is \fBronn\fR(1)\. For an example without using external utilities, see \fIExample\fR in \fBfisher help plugins\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-a \-\-all\fR
List all available commands and guides\.
.
.TP
\fB\-g \-\-guides[=*bare*]\fR
List guides / tutorials\. Use \fIbare\fR to generate easy to parse output\.
.
.TP
\fB\-\-commands[=*bare*]\fR
List commands\. This is the default behavior of \fBfisher help\fR\. Use \fIbare\fR to generate easy to parse output\.
.
.TP
\fB\-\-usage[=*command*]\fR
Display usage help for \fIcommand\fR\. To teach Fisherman how to display help for your command, \fIcommand\fR must implement a \fB\-h\fR flag\.
.
.TP
\fB\-h \-\-help\fR
Show usage help\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Show all the available documentation\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher help \-a
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
Show documentation about help\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher help help
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
Show usage help for all Fisherman commands\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher help \-\-commands=bare | fisher help \-\-usage
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
\fBman\fR(1), \fBfisher\fR(1)
