.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER" "1" "January 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\fR \- Fish Plugin Manager
.
.SH "SYNOPSIS"
\fBfisher\fR \fIcommand\fR [\fIoptions\fR] [\fB\-\-version\fR] [\fB\-\-help\fR]
.
.br
\fBfisher\fR \fB\-\-list=cache|enabled|disabled\fR
.
.br
\fBfisher\fR \fB\-\-file\fR=\fIfishfile\fR
.
.br
.
.SH "DESCRIPTION"
Fisherman is a plugin manager and CLI toolkit for \fBfish(1)\fR to help you build powerful utilities and share your code easily\.
.
.P
The following commands are available out of the box: \fIinstall\fR, \fIuninstall\fR, \fIupdate\fR, \fIsearch\fR and \fIhelp\fR\. See \fBfisher help <command>\fR for information about each command\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-list[=bare|enabled|disabled]\fR
List plugins according to the given category\. List plugins in the cache by default\. Enabled plugins are prepended with a \fB*\fR character\. To list plugins without the \fB*\fR character use \fB\-\-list=bare\fR\.
.
.TP
\fB\-f \-\-file=fishfile\fR
Read \fIfishfile\fR and display its contents\. If \fIfishfile\fR is null or an empty string, your user \fIfishfile\fR in \fB$fisher_file\fR will be shown instead\. Use a dash \fB\-\fR to read from the standard input\. Other formats such as the oh\-my\-fish bundle files are supported as well\.
.
.TP
\fB\-v \-\-version\fR
Show version information\. Fisherman\'s current version can be found in the VERSION file at the root of the project\. The version scheme is based in \fBSemantic Versioning\fR and uses Git annotated tags to track releases\.
.
.TP
\fB\-h \-\-help\fR
Show usage help\.
.
.SH "CUSTOM COMMANDS"
A Fisherman command is a function that you invoke using the \fBfisher\fR CLI utility\. By convention, any function like \fBfisher_<my_command>\fR is recognized as a Fisherman command\. You can create plugins that add new commands this way\. See \fBfisher help commands\fR and \fBfisher help plugins\fR for more information\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Install plugins\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher install fishtape shark
.
.fi
.
.IP "" 0
.
.TP
Install plugins from a \fIfishfile\fR or bundle:

.
.IP "" 4
.
.nf

fisher \-\-file=path/to/bundle | fisher install
.
.fi
.
.IP "" 0
.
.SH "AUTHORS"
Fisherman was created by Jorge Bucaran \fIj@bucaran\.me\fR\.
.
.P
See AUTHORS file for the complete list of contributors\.
.
.SH "SEE ALSO"
fisher help tour
.
.br
fisher help help
.
.br
fisher help update
.
.br
fisher help search
.
.br
fisher help config
.
.br
fisher help install
.
.br
fisher help plugins
.
.br
fisher help commands
.
.br
fisher help fishfile
.
.br
fisher help uninstall
.
.br

