.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FISHER\-UPDATE" "1" "February 2016" "" "fisherman"
.
.SH "NAME"
\fBfisher\-update\fR \- Update Fisherman and Plugins
.
.SH "SYNOPSIS"
fisher \fBupdate\fR [\fIplugins\fR \.\.\.] [\fB\-\-quiet\fR] [\fB\-\-help\fR]
.
.br
.
.SH "USAGE"
fisher \fBupdate\fR \fIurl\fR \.\.\.
.
.br
fisher \fBupdate\fR \fIname\fR \.\.\.
.
.br
fisher \fBupdate\fR \fIpath\fR \.\.\.
.
.br
fisher \fBupdate\fR \fIowner/repo\fR \.\.\.
.
.br
.
.SH "DESCRIPTION"
Update one or more plugins, by name, URL or a local path\. If no arguments are given, update Fisherman to the latest release\. If you try to update a plugin that is currently disabled, but present in the cache, it will be updated and then enabled\. Use a dash \fB\-\fR to read from the standard input\.
.
.P
One exception to the process described above is updating a prompt which is not the current one\. In this case the repository is updated, but it will not be activated as that is probably not what the user wants\.
.
.P
If a plugin is missing dependencies, they will be installed\. If any dependencies are already installed they will not be updated\. See \fBPlugins\fR in \fBfisher help fishfile\fR\.
.
.SH "OPTIONS"
.
.TP
\fB\-q \-\-quiet\fR
Enable quiet mode\.
.
.TP
\fB\-h \-\-help\fR
Show usage help\.
.
.SH "EXAMPLES"
.
.IP "\(bu" 4
Update Fisherman
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher update
.
.fi
.
.IP "" 0
.
.IP "\(bu" 4
Update all the plugins in the cache\.
.
.IP "" 0
.
.IP "" 4
.
.nf

fisher \-\-list | fisher update \-
.
.fi
.
.IP "" 0
.
.SH "SEE ALSO"
fisher(1)
.
.br
fisher help plugins
.
.br

