.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SPIN" "1" "March 2016" "" "fisherman"
.
.SH "NAME"
\fBspin\fR \- Background job spinner
.
.SH "SYNOPSIS"
\fBspin\fR \fIcommands\fR [\fB\-\-style\fR=\fImix\fR|\fIarc\fR|\fIstar\fR|\fIpipe\fR|\fIflip\fR|\fIbounce\fR|\fIbar1~3\fR]
.
.br
\fBspin\fR \fIcommands\fR [\fB\-\-error\fR=file] [\fB\-\-format\fR=format] [\fB\-\-help\fR]
.
.SH "DESCRIPTION"
\fBSpin\fR is a terminal spinner and progress bar indicator for fish\.
.
.SH "USAGE"
.
.nf

spin "sleep 1"
.
.fi
.
.P
Spin interprets any output to standard error as failure\. Use \-\-error=\fIfile\fR to redirect the standard error output to \fIfile\fR\.
.
.IP "" 4
.
.nf

if not spin \-\-style=pipe \-\-error=debug\.txt "curl \-sS $URL"
    return 1
end
.
.fi
.
.IP "" 0
.
.SH "Options"
.
.TP
\-s, \-\-style=\fIstyle\fR|\fIstring\fR
Use \fIstring\fR to slice the spinner characters\. If you don\'t want to display the spinners, use \-\-style=\fI""\fR\.
.
.TP
\-f, \-\-format=\fIformat\fR
Use \fIformat\fR to customize the spinner display\. The default format is \fB" @\er"\fR where \fB@\fR represents the spinner token and \fB\er\fR a carriage return, used to refresh (erase) the line\.
.
.TP
\-\-error=\fIfile\fR
Write the standard error output to a given \fIfile\fR\.
.
.TP
\-h, \-\-help
Show usage help\.
.
.SS "Customization"
Replace the default spinner with your own string of characters\. For example, \-\-style=\fI12345\fR will display the numbers from 1 to 5, and \-\-style=\fI\.\fR \-\-format=\fI@\fR an increasing sequence of dots\.
